feat(collator): add check value flow on finalize
broxus/tycho pull request #375
Opened 2024-10-24 08:04 UTC by serejkaaa512

2024-11-12 12:18 UTC, 0xdeafbeef approved these changes
lgtm

2024-11-12 16:51 UTC, SmaGMan commented
Should run the check by param in node config. Default should be off.

2024-11-13 10:49 UTC, SmaGMan requested changes
And squash commits, pls.

2024-11-13 10:49 UTC, SmaGMan commented on collator/src/collator/do_collate.rs
> +                    check_value_flow,
Should pass full `CollatorConfig` here

2024-11-13 11:28 UTC, SmaGMan approved these changes

2024-11-13 11:52 UTC, merged