fix(validator): session signatures storage
broxus/tycho pull request #428
Opened 2024-11-07 12:59 UTC by drmick

2024-11-13 09:20 UTC, drmick commented on collator/src/validator/impls/std_impl/session.rs
> +                Some(cached) => self.reuse_signatures(block_id, cached.clone()).await,
refactored

2024-11-13 09:20 UTC, drmick commented on collator/src/validator/impls/std_impl/session.rs
> +            .remove(&block_id.seqno)
refactored

2024-11-14 10:53 UTC, SmaGMan commented on collator/src/validator/impls/std_impl/session.rs
> -        // NOTE: To eliminate the gap inside exchange routine, we can remove cached signatures
Let's move this comments to a place were we insert into block signatures and remove from cached signatures.

2024-11-14 10:59 UTC, SmaGMan requested changes

2024-11-14 10:59 UTC, SmaGMan commented on collator/src/validator/impls/std_impl/session.rs
> +                anyhow::bail!(
Should not just remove TODO. Let's panic here: https://broxus.youtrack.cloud/articles/DNODE-A-5#task-v004

2024-11-14 13:50 UTC, SmaGMan approved these changes

2025-04-17 12:17 UTC, Rexagon commented
Issue seems to be fixed by updating dependencies

2025-04-17 12:17 UTC, closed without merging