feat(collator): add top shard blocks to block debug info
broxus/tycho pull request #459
Opened 2024-11-14 12:31 UTC by serejkaaa512

2024-11-14 12:35 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +    pub top_shard_blocks_info: Option<&'a FastHashMap<ShardIdent, Box<ShardDescription>>>,
Let's rename to `mc_top_shards`

2024-11-14 12:37 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +                "shard_description",
Let's rename to `shard_descr`

2024-11-14 12:38 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +        let mut s = f.debug_struct("TopShardBlocksDebugInfo");
Let's rename to `McTopShards`

2024-11-14 12:39 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +pub struct TopShardBlocksDescriptionDebugInfo<'a>(pub &'a ShardDescription);
Let's rename to `DebugShardDescription`

2024-11-14 12:40 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +        f.debug_struct("TopShardBlocksDescription")
Let's rename to `DebugShardDescription`

2024-11-14 12:41 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +            .field("seqno", &DebugDisplay(self.0.seqno))
Do not need to wrap simple types

2024-11-14 13:03 UTC, SmaGMan commented on collator/src/collator/debug_info.rs
> +        f.debug_struct("DebugShardDescription")
Rename here to `ShardDescription`

2024-11-15 10:16 UTC, 0xdeafbeef requested changes

2024-11-15 12:59 UTC, 0xdeafbeef commented on collator/src/collator/build_block.rs
> +                mc_top_shards: collation_data.shards().ok(),
But it's useless to return `Result<T>` if you always convert it to `Option<T>`. You allocate `Box<dyn Error>` without a need.

2024-11-15 15:16 UTC, SmaGMan commented on collator/src/collator/build_block.rs
> +                mc_top_shards: collation_data.shards().ok(),
Now we use method that returns `Option<T>`.

2024-11-21 16:13 UTC, SmaGMan approved these changes

2024-11-21 16:14 UTC, 0xdeafbeef approved these changes

2024-11-21 17:06 UTC, merged