Refactor/genesis info
broxus/tycho pull request #510
Opened 2024-12-27 10:35 UTC by Mododo

2025-01-06 23:57 UTC, Rexagon requested changes

2025-01-06 23:57 UTC, Rexagon commented on Cargo.toml
> +everscale-types = { git = "https://github.com/broxus/everscale-types.git" }
Pin a specific commit as a revision for types

2025-01-06 23:57 UTC, Rexagon commented on collator/src/collator/do_collate/finalize.rs
> +            if mp_cfg_override.genesis_info.start_round >= consensus_info.genesis_info.start_round
Maybe impl an `Ord`/`PartialOrd` trait for `GenesisInfo`? Or at least a single method to determine that info is "after"

2025-01-06 23:57 UTC, Rexagon commented on collator/src/manager/mod.rs
> +            if mp_cfg_override.genesis_info.start_round
^ see cmp comment

2025-01-06 23:57 UTC, Rexagon commented on collator/src/mempool/impls/std_impl.rs
> +                genesis.start_round >= new_cx.consensus_info.genesis_info.start_round
^ see cmp comment

2025-01-07 11:12 UTC, Mododo commented on collator/src/collator/do_collate/finalize.rs
> +            if mp_cfg_override.genesis_info.start_round >= consensus_info.genesis_info.start_round
unfortunately, would like to have comparison in tycho repo so it could be easily changed in place, while need to have the struct in types to be accessible across crates

2025-01-07 11:14 UTC, Mododo commented on Cargo.toml
> +everscale-types = { git = "https://github.com/broxus/everscale-types.git" }
the latest commit in this PR (including this line and the one in `Cargo.lock`) should be removed, when the new version of types is ready. or do we want to use the patch?

2025-01-07 13:25 UTC, Mododo commented on Cargo.toml
> +everscale-types = { git = "https://github.com/broxus/everscale-types.git" }
done; patch with revision to merge this commit earlier than next types version

2025-01-07 13:27 UTC, Mododo commented on collator/src/collator/do_collate/finalize.rs
> +            if mp_cfg_override.genesis_info.start_round >= consensus_info.genesis_info.start_round
done; added a single responsibility method

2025-01-07 17:13 UTC, Rexagon approved these changes

2025-01-07 18:30 UTC, merged